# Site
repository: agopwns/agopwns.github.io
favicon: images/favicon.ico

# Personal info
name: í•˜ì„±ì¤€
title: SENIOR SW ENGINEER
       
email: agopwns@gmail.com
thread: www.threads.net/@nomadjun195

# Dark Mode
darkmode: never

# Social links
github_username: agopwns
instagram_username: nomadjun195

# youtube_username: channel/UC9gV3AO0ulWIbKqg9FYDSnA

# About Section
# about_title: About Me
about_profile_image: images/IMG_2372.jpg
about_content: 
  ì•ˆë…•í•˜ì„¸ìš”. ì €ëŠ” <mark>ì§€ì†ì ì¸ ë°°ì›€</mark> <mark>ì»¤ë®¤ë‹ˆì¼€ì´ì…˜</mark> <mark>í˜‘ì—…</mark>  <mark>ìƒê°</mark> ì„ ê°€ì¥ ì¤‘ìš”í•˜ê²Œ ì—¬ê¸°ëŠ” 9ë…„ì°¨ ê°œë°œì í•˜ì„±ì¤€ì…ë‹ˆë‹¤. <br /> 
  <br />
  ìƒˆë¡œìš´ ë°°ì›€ê³¼ ëŠ¥ë™ì ì¸ ì»¤ë®¤ë‹ˆì¼€ì´ì…˜ì„ í†µí•´ ì„¸ìƒì— í•„ìš”í•œ ì„œë¹„ìŠ¤ë¥¼ ë§Œë“œëŠ” ê²ƒì„ ì¢‹ì•„í•©ë‹ˆë‹¤. <br />
  <br />
  ê¸°ìˆ ë„ ì¤‘ìš”í•˜ì§€ë§Œ ìœ ì €ì™€ íšŒì‚¬ê°€ ì›í•˜ëŠ” ê²ƒì´ ë¬´ì—‡ì¸ì§€ í•­ìƒ ê³ ë¯¼í•˜ì—¬ ì„œë¹„ìŠ¤ì— ì ìš©í•˜ëŠ” ì‚¬ëŒì´ ë˜ê³ ì ë…¸ë ¥í•©ë‹ˆë‹¤. <br />
  <br />
  í˜„ì¬ ìœ„ì¹˜&nbsp; ğŸ“ &nbsp;Seoul, Korea<br />
  ê·¼ë¬´ í˜•íƒœ&nbsp; ğŸ§‘ğŸ»â€ğŸ’» &nbsp;ì›ê²© ê·¼ë¬´ (í•œêµ­ ì‹œê°„ 10ì‹œ ~ 16ì‹œ)<br />
  ì£¼ë ¥ ê¸°ìˆ &nbsp; ğŸ•¹ï¸ &nbsp;AWS,  Next.js,  Flutter,  Mobile,  Supabase,  Node.js,  Django<br />
  <br /><br />
  Update 2025-02-12

# Experience Section
# experience_title: Experience

# Projects Section
# projects_title: Projects

# Education Section
# educaton_title: Education

# More Section
# more_title: Side Project
# more_content: | # this will include new lines to allow paragraphs
#   Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#    - Rock climbing
#    - Gaming
#    - Knitting
#    - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
